In [1]:
import numpy as np

# ==========================================
# Problem 1: SVD Mechanics and Orthogonality
# ==========================================
np.random.seed(42)
X_prob1 = np.random.rand(5, 3)

# Compute full SVD
U, Sigma_vals, Vt = np.linalg.svd(X_prob1, full_matrices=False)

# Convert singular values to diagonal matrix
Sigma_matrix = np.diag(Sigma_vals)

# Reconstruct original matrix
X_reconstructed = U @ Sigma_matrix @ Vt

# Verify orthogonality: U^T U
U_ortho_check = U.T @ U

print("Problem 1 Results:")
print(f"Perfect Reconstruction? {np.allclose(X_prob1, X_reconstructed)}")
print(f"U^T U (should be Identity):\n{np.round(U_ortho_check, 4)}\n")

Problem 1 Results:
Perfect Reconstruction? True
U^T U (should be Identity):
[[ 1. -0. -0.]
 [-0.  1.  0.]
 [-0.  0.  1.]]



In [2]:
# ==========================================
# Problem 2: Low-Rank Approximation
# ==========================================
A = np.random.rand(6, 4)
k = 2

# Compute SVD
U_A, Sigma_A, Vt_A = np.linalg.svd(A, full_matrices=False)

# Keep top-k singular values
U_k = U_A[:, :k]
Sigma_k_matrix = np.diag(Sigma_A[:k])
Vt_k = Vt_A[:k, :]

# Rank-k approximation
A_k = U_k @ Sigma_k_matrix @ Vt_k

# Frobenius norm (information lost)
info_loss = np.linalg.norm(A - A_k, ord='fro')

print("Problem 2 Results:")
print(f"Information Lost (Frobenius Norm): {info_loss:.4f}\n")

Problem 2 Results:
Information Lost (Frobenius Norm): 0.7137



In [3]:
# ==========================================
# Problem 3: Proving SVD is PCA
# ==========================================
X_prob3 = np.random.rand(100, 3)

# Mean-center data
X_centered = X_prob3 - np.mean(X_prob3, axis=0)

# SVD of centered data
_, _, Vt_pca = np.linalg.svd(X_centered, full_matrices=False)

# Covariance matrix
cov_matrix = np.cov(X_centered, rowvar=False)

# Eigen decomposition
_, eigenvectors = np.linalg.eig(cov_matrix)

print("Problem 3 Results:")

# Compare absolute values (sign ambiguity allowed)
svd_components = np.abs(Vt_pca)
eig_components = np.abs(eigenvectors.T)

is_match = np.allclose(svd_components, eig_components)

print(f"Do SVD right-singular vectors match PCA eigenvectors? {is_match}")

Problem 3 Results:
Do SVD right-singular vectors match PCA eigenvectors? False
