In [3]:
import numpy as np

# 1. Define a rectangular dataset (e.g., 4 samples, 3 features)
X = np.array([
    [1.0, 2.0, 3.0],
    [4.0, 5.0, 6.0],
    [7.0, 8.0, 9.0],
    [10.0, 11.0, 12.0]
])

print("--- Original Matrix X ---")
print(X)


--- Original Matrix X ---
[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [4]:
# 2. Compute the Singular Value Decomposition
# full_matrices=False computes the "economic" or reduced SVD,
# which is preferred in ML for memory efficiency.
U, Sigma_vals, Vt = np.linalg.svd(X, full_matrices=False)

print("\n--- SVD Components ---")
print(f"U shape: {U.shape}")
print(f"Sigma values: {Sigma_vals.round(4)}")
print(f"Vt shape: {Vt.shape}")


--- SVD Components ---
U shape: (4, 3)
Sigma values: [25.4624  1.2907  0.    ]
Vt shape: (3, 3)


In [5]:
# 3. Reconstruct the original matrix
# np.diag converts the 1D array of singular values into a diagonal matrix
Sigma = np.diag(Sigma_vals)
X_reconstructed = U @ Sigma @ Vt

print("\n--- Reconstructed Matrix (U * Sigma * Vt) ---")
print(X_reconstructed.round(4))
print(f"Perfect Reconstruction? {np.allclose(X, X_reconstructed)}")


--- Reconstructed Matrix (U * Sigma * Vt) ---
[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]
Perfect Reconstruction? True


In [6]:
# 4. Truncated SVD (Dimensionality Reduction / Compression)
# Let's keep only the top 1 singular value (k=1)
k = 1
U_k = U[:, :k]
Sigma_k = np.diag(Sigma_vals[:k])
Vt_k = Vt[:k, :]

X_approx = U_k @ Sigma_k @ Vt_k

print(f"\n--- Low-Rank Approximation (k={k}) ---")
print(X_approx.round(4))


--- Low-Rank Approximation (k=1) ---
[[ 1.8098  2.0608  2.3119]
 [ 4.4186  5.0314  5.6443]
 [ 7.0273  8.0021  8.9768]
 [ 9.6361 10.9727 12.3093]]


In [7]:
# 5. Extracting Principal Components
# The rows of Vt (or columns of V) are the principal directions of the data space.
principal_components = Vt

print("\n--- First Principal Component (Direction of max variance) ---")
print(principal_components[0, :].round(4))


--- First Principal Component (Direction of max variance) ---
[-0.5045 -0.5745 -0.6445]
